### ISSUE TITLE
put a list of music tracks being played in the radio

### ISSUE THREAD

**Issue by sayanee** [webuildsg/live#87]

**Comment by notthetup** [comment]
The CC music being played on our radio is.

## mp3 (Chrome/FF/Safari)

## ogg (Chromium/FF/etc on Linux)
- http://www.musicmanumit.com/2014/04/music-only-140418-music-manumit-podcast.html
- http://www.musicmanumit.com/2014/04/music-only-140412-music-manumit-podcast.html
- http://www.musicmanumit.com/2014/03/music-only-140321-music-manumit-podcast.html
- http://www.musicmanumit.com/2014/03/music-only-140328-music-manumit-podcast.html
