### ISSUE TITLE
artwork not showing on overcast fm

### ISSUE THREAD

**Issue by sayanee** [webuildsg/live#97]
thanks @burnflare for notifying:

![image](https://cloud.githubusercontent.com/assets/413879/18990365/e80f549c-8743-11e6-8ed1-ea509cc397cf.png)

**Comment by sayanee** [comment]
closed with 6f5f562072ef35a21d972a4e50e22586824deb18 thanks @notthetup 🎐

**Comment by burnflare** [comment]
I unsubscribed from the podcast and added it again in Overcast. Still doesn't have an artwork for some reason

![untitled](https://cloud.githubusercontent.com/assets/104150/19020757/3aa813a0-88e4-11e6-8916-b2e3de28b3fc.png)

**Comment by notthetup** [comment]
Hmm.. Let me get overcast and try this out.

**Comment by notthetup** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/553140/19020986/c9998f9e-88e9-11e6-9e2c-c638d5bd9c0e.png)

I tried it on iPad and it kinda worked. Or?

**Comment by notthetup** [comment]
![img_3421](https://cloud.githubusercontent.com/assets/553140/19021002/69ca4dd2-88ea-11e6-91c8-1d9818947e44.PNG)
